generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.uq.edu.au
  https: true
  tls_version: TLSv1.3
  cert_expires: Nov 24 23:59:59 2026 GMT
  hsts: false
- host: espace.library.uq.edu.au
  https: true
  tls_version: TLSv1.3
  cert_expires: Sep 11 23:59:59 2026 GMT
  hsts: null
- host: data.uq.edu.au
  https: true
  tls_version: TLSv1.3
  cert_expires: Aug 16 18:45:20 2026 GMT
  hsts: null
domains:
- domain: uq.edu.au
  dnssec: false
  caa:
  - 0 issue "letsencrypt.org"
  - 0 issue "digicert.com"
  - 0 iodef "mailto:certificates@uq.edu.au"
  - 0 issue "amazon.com"
  - 0 issue "globalsign.com"
  - 0 issue "sectigo.com"
  spf: true
  dmarc: true
  dmarc_policy: quarantine
